export const cafe = {
  name: "Concordia's Cafe",
  lockup: "CONCORDIA'S CAFE — BF HOMES",
  tagline: "OUR HOME, YOUR HOME",
  addressLine: "106 Aguirre Ave, BF Homes",
  addressFull: "106 Aguirre Ave, BF Homes, Paranaque",
  hoursLine: "DAILY 7AM-12MN",
  hoursPlain: "Daily, 7am-12mn",
  phoneDisplay: "0962 884 3971",
  phoneHref: "tel:+639628843971",
  facebook: "https://www.facebook.com/concordiascafe",
  instagram: "https://www.instagram.com/concordiascafebf/",
  instagramHandle: "@concordiascafebf",
  mapsQuery:
    "https://www.google.com/maps/search/?api=1&query=106+Aguirre+Ave+BF+Homes+Paranaque",
  mapsEmbed:
    "https://maps.google.com/maps?q=106%20Aguirre%20Ave%2C%20BF%20Homes%2C%20Para%C3%B1aque&z=16&output=embed",
  disclaimer: "Demo site by KantoCo — sample only. Not real client work.",
  lookPass: "SAMPLE | look pass | not live",
  photoCredit: "photo: Zoy / Concordia IG | public visitor ref",
} as const;

export const walkIn = [
  {
    key: "facade",
    src: "/demos/concordias-cafe/walk-in/facade.webp",
    alt: "Night storefront of Concordia's Cafe on Aguirre Ave. Photo: Zoy to the World.",
    kicker: cafe.tagline,
    title: "106 AGUIRRE",
    line: cafe.lockup,
    kind: "photo",
  },
  {
    key: "glass",
    src: "/demos/concordias-cafe/walk-in/alfresco.webp",
    alt: "Al fresco patio and glass door at Concordia's Cafe. Photo: Zoy to the World.",
    kicker: "THE GLASS",
    title: "THROUGH",
    line: "The door on Aguirre.",
    kind: "photo",
  },
  {
    key: "through",
    src: "/demos/concordias-cafe/walk-in/glass.jpg",
    alt: "Inside Concordia's Cafe looking back at the glass doors and vines. Concordia Instagram.",
    kicker: "INSIDE",
    title: "",
    line: "",
    kind: "photo",
  },
  {
    key: "room",
    src: "/demos/concordias-cafe/walk-in/room.webp",
    alt: "Daylight hall at Concordia's Cafe. Concrete, white trusses, fluted tables. Photo: Zoy to the World.",
    kicker: "INSIDE",
    title: "THE ROOM",
    line: "Come hang.",
    italic: true,
    kind: "photo",
  },
  {
    key: "cup",
    src: "/demos/concordias-cafe/walk-in/cup.jpg",
    alt: "Takeaway cup with Concordia's navy CON/COR/DIA'S sleeve. Concordia Instagram.",
    kicker: "THE DRINK",
    title: "COME HANG",
    line: "",
    kind: "cup",
  },
] as const;
