export const cafe = {
  name: "Concordia's Cafe",
  lockup: "CONCORDIA'S CAFE — BF HOMES",
  tagline: "OUR HOME, YOUR HOME",
  addressLine: "106 Aguirre Ave, BF Homes",
  addressFull: "106 Aguirre Ave, BF Homes, Paranaque",
  hoursLine: "DAILY 7AM-12MN",
  hoursPlain: "Daily, 7am-12mn",
  phoneDisplay: "0962 884 3971",
  phoneHref: "tel:+639628843971",
  facebook: "https://www.facebook.com/concordiascafe",
  instagram: "https://www.instagram.com/concordiascafebf/",
  instagramHandle: "@concordiascafebf",
  mapsQuery:
    "https://www.google.com/maps/search/?api=1&query=106+Aguirre+Ave+BF+Homes+Paranaque",
  mapsEmbed:
    "https://maps.google.com/maps?q=106%20Aguirre%20Ave%2C%20BF%20Homes%2C%20Para%C3%B1aque&z=16&output=embed",
  disclaimer: "Demo site by KantoCo — sample only. Not real client work.",
  lookPass: "SAMPLE | look pass | not live",
  photoCredit: "photo: Zoy / Concordia IG | public visitor ref",
} as const;

export const walkIn = [
  {
    key: "facade",
    src: "/demos/concordias-cafe/night-facade.webp",
    alt: "Night storefront of Concordia's Cafe on Aguirre Ave. Photo: Zoy to the World.",
    kicker: cafe.tagline,
    title: "106 AGUIRRE",
    line: cafe.lockup,
    wash: "default",
  },
  {
    key: "open",
    src: "/demos/concordias-cafe/walk-in/06-open.jpg",
    alt: "Glass entry at Concordia's Cafe. Visitor still, Concordia Instagram.",
    kicker: "THE GLASS",
    title: "",
    line: "",
    wash: "soft",
  },
  {
    key: "interior",
    src: "/demos/concordias-cafe/walk-in/05-interior.jpg",
    alt: "Daylight interior looking toward the glass storefront. Visitor still, Concordia Instagram.",
    kicker: "INSIDE",
    title: "THE ROOM",
    line: "Come hang.",
    italic: true,
    wash: "default",
  },
  {
    key: "cup",
    src: "/demos/concordias-cafe/walk-in/02-cup.jpg",
    alt: "Takeaway cup with Concordia's navy sleeve. Visitor still, Concordia Instagram.",
    kicker: "THE DRINK",
    title: "COME HANG",
    line: "",
    wash: "default",
  },
] as const;
